title: Valentin-Marian Voilean
email: contact@valentinvoilean.com
description: >
  Valentin-Marian Voilean portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://valentinvoilean.com"
github_username:  valentinvoilean

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
