title: Valentin-Marian Voilean
locale: en_US
url: "http://valentinvoilean.com"
email: contact@valentinvoilean.com
description: Valentin-Marian Voilean portfolio

github_username:  valentinvoilean

permalink:   /:categories/:title/
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

plugins_dir:
  - jekyll-feed

gems: [normalize-scss, susy]



exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
